version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"

  # Enable version updates for npm (if we add any Node.js tools later)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"

  # Enable version updates for Docker (if we add containerization later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername" 