name: Version Bump and Tag

# DISABLED: This workflow causes divergent branches
# Uncomment the following section if you want automatic version bumping
# on:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - '**.md'
#       - '.gitignore'
#       - 'LICENSE'
#       - 'SECURITY.md'
#       - 'CONTRIBUTING.md'

# Manual trigger only
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to (e.g., 1.0.4)'
        required: true
        default: '1.0.4'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update version
        id: update_version
        run: |
          NEW_VERSION="${{ github.event.inputs.version }}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Updating to version: $NEW_VERSION"
          
          # Update CMakeLists.txt
          sed -i "s/project(HACKED VERSION [0-9]*\.[0-9]*\.[0-9]*)/project(HACKED VERSION $NEW_VERSION)/" CMakeLists.txt
          
          # Update Info.plist for macOS
          sed -i "s/<string>[0-9]*\.[0-9]*\.[0-9]*<\/string>/<string>$NEW_VERSION<\/string>/g" Info.plist

      - name: Create and push changes
        run: |
          git add CMakeLists.txt Info.plist
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push origin main

      - name: Create and push tag
        run: |
          git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
          git push origin "v$NEW_VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body: |
            ## 🎉 HACKED - Belgian System Simulation v${{ env.NEW_VERSION }}
            
            ### 📦 Downloads
            - **Linux (x64)**: HACKED-linux-x64.tar.gz
            - **macOS (x64)**: HACKED-macos-x64.tar.gz  
            - **Windows (x64)**: HACKED-windows-x64.tar.gz
            
            ### 🚀 Installation
            1. Download the appropriate tarball for your platform
            2. Extract: `tar -xzf HACKED-[platform]-x64.tar.gz`
            3. Run: `./HACKED` (Linux/macOS) or `HACKED.exe` (Windows)
            
            ### 🔧 Features
            - Fullscreen Belgian system simulation
            - Automatic screenshots after 30 seconds
            - Exit with password: "chicon"
            
            ### ⚠️ Safety Notice
            This is a harmless simulation application for educational purposes only.
            No actual system hacking occurs.
          draft: true
          prerelease: false 